version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: patientrecordserver
    container_name: patientrecordserver
    ports:
      - "8001:8000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: ${NODE_ENV}
    command: yarn start

networks:
  app-network:
    driver: bridge
